---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"
  name: clickhouse
- src: git@github.com:Roma-EDU/vector-role.git
  scm: git
  version: "master"
  name: vector
- src: git@github.com:Roma-EDU/lighthouse-role.git
  scm: git
  version: "master"
  name: lighthouse