---
- name: Install Lighthouse
  hosts: lighthouse
  pre_tasks:
    - name: Install Lighthouse | Install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  roles:
    - nginx
    - lighthouse
- name: Install Vector
  hosts: vector
  roles:
    - vector
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
